reference_url: 'https://rt.skymesh.net.au/Ticket/Display.html?id='
vocus_url: 'https://members.wcg.net.au/view_ticket.php?id='
nbn_url: 'https://www1.nbnco.com.au/online_customers/page/home?search='
service_types:
- fttn/b
- fttp
- hfc
- lts
- fw
- voip/univ
- pstn
- legacy service
quick_notes:
- OFFLINE |
- DROPOUTS |
- SPEED |
- BROWSING |
- OUTAGE |
- Online?
- Usage?
- Contact?
- Work done?
- NBN response?
- Vocus response?