reference_url: 'place_ref_url'
vocus_url: 'place_vocus_url'
nbn_url: 'place_nbn_url'
service_types:
- fttn/b
- fttp
- hfc
- lts
- fw
- voip/univ
- pstn
- legacy service
quick_notes:
- OFFLINE |
- DROPOUTS |
- SPEED |
- BROWSING |
- OUTAGE |
- Online?
- Usage?
- Contact?
- Work done?
- NBN response?
- Vocus response?
- 2DaysWarning