reference_url: 'https://www.google.com.au/search?q='
service_type_url: 'https://www.google.com.au/search?q='
service_types:
- fttn/b
- fttp
- hfc
- lts
- voip/univ
- legacy service
quick_notes:
- OFFLINE |
- DROPOUTS |
- SPEED |
- Online?
- Usage?
- Contact?
- Work done?